### ISSUE TITLE
(rpc-server): Query_view_state - Error messages mismatch

### ISSUE THREAD

**Issue by kobayurii** [near/read-rpc#157]
The errors are a little different.
 
rpc-server
```
{
    "info": {
        "block_hash": {block_hash}, 
        "block_height": {block_height}, 
        "requested_account_id": {account_id}
    }, 
    "name": "UNKNOWN_ACCOUNT"
}
```

Near RPC
```
{"info": {"requested_shard_id": {shard_id}}, "name": "UNAVAILABLE_SHARD"}}.
```

I'm not sure we can set up an exact error match here.

**Comment by frolvanya** [comment]
Do you still have an information about account id and block that was used to receive these errors? "UNAVAILABLE_SHARD" looks like an internal rpc error to me that shouldn't be possible to replicate with our DB structure. Also, this issue might relate to #302 and it was already fixed in a recent PR #303
