### ISSUE TITLE
Additional metrics to measure proxy calls (archival)

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#176]
We got an internal request to measure the number of proxy calls we make.

The main goal is to identify how hard we're touching the ArchivalRPC to judge whether all the proxies we do in this regard are reasonable. Thus, we could adjust the logic (if necessary) to reduce the number of such calls.

**Comment by kobayurii** [comment]
Proxying to archive nodes we have only 2 cases:
1. When we use `shadow_data_consistency`.
2. In the QUERY.VIEW_STATE method with the `include_proof` flag. 

In the first case, we don't need to worry about calling archive nodes because the feature `shadow_data_consistency` is used only for debugging the service and **should not be enabled on the production server**.

In the other case, I added an `archive_proxy_query_view_state_with_include_proofs` metric which counts the number of requests redirected to archive nodes.

**Comment by kobayurii** [comment]
https://github.com/near/read-rpc/pull/177
