### ISSUE TITLE
(rpc-server): Result mismatch for an account with no keys in state

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#302]
@evgenykuzyakov reported:

Found inconsistency between the read-rpc and a regular rpc. When you query ViewState for an account without any keys in the state, it returns HandlerError(UnknownAccount while regular RPC returns empty array of keys

---

I suspect this is related to the way we handle state changes. If the account never had any keys in a state we assume such account does not exist. Since we don't keep a list of accounts it might be a tricky task to solve

**Comment by frolvanya** [comment]
The first thing that came up to my mind is to add an extra check in case of ViewState call failure:
ViewState (fail) -> ViewAccount (if fails with unknown account error, then we display the initial error. Otherwise, return an empty array)

Is it an appropriate fix or it's better to try to come up with a solution that doesn't require an extra call to DB?
